// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using costbenefi.Data;

#nullable disable

namespace costbenefi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250708221232_AddBarcodeAndIVAFields")]
    partial class AddBarcodeAndIVAFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("costbenefi.Models.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlertaStockBajo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreArticulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioConIVA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioPorUnidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioPorUnidadBase")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioSinIVA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockAntiguo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockNuevo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("NombreArticulo");

                    b.HasIndex("Proveedor");

                    b.ToTable("RawMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
