// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using costbenefi.Data;

#nullable disable

namespace costbenefi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250712165607_EliminacionLogica")]
    partial class EliminacionLogica
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("costbenefi.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioConIVA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioSinIVA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaMovimiento");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("TipoMovimiento");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("costbenefi.Models.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AlertaStockBajo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("FactorConversion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(1m);

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoEliminacion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreArticulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioBaseConIVA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioBaseSinIVA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioConIVA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioPorUnidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioPorUnidadBase")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecioSinIVA")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockAntiguo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StockNuevo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnidadBase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioEliminacion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("CodigoBarras");

                    b.HasIndex("Eliminado");

                    b.HasIndex("FechaEliminacion");

                    b.HasIndex("NombreArticulo");

                    b.HasIndex("Proveedor");

                    b.HasIndex("UnidadMedida");

                    b.HasIndex("UsuarioEliminacion");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("costbenefi.Models.Movimiento", b =>
                {
                    b.HasOne("costbenefi.Models.RawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RawMaterial");
                });
#pragma warning restore 612, 618
        }
    }
}
